export type CSSUnit =
  // Length
  | "%"
  | "ch"
  | "cm"
  | "em"
  | "ex"
  | "in"
  | "mm"
  | "pc"
  | "pt"
  | "px"
  | "rem"
  | "vh"
  | "vmax"
  | "vmin"
  | "vw"
  //Angle
  | "deg"
  | "grad"
  | "rad"
  | "turn";

type CSSVariableOptions<TValue> =
  | { value: TValue | CSSVariable<TValue>; unit: CSSUnit }
  | { value: TValue | CSSVariable<TValue> };
type CSSVariableValue = string | number;

export class CSSVariable<TValue = CSSVariableValue> extends (
  // Inherit from String to be compatible to most CSS-in-JS solutions
  // Hacky cast to any for reduced autocomplete
  String as any as { new(base: string): { toString: () => string } }
) {
  private readonly unit: CSSUnit | "";
  /** Name e.g. `--baseSize` */
  readonly name: string;

  /** 
   * Creates a new CSS Variable with a unique autogenerated name 
   * 
   * E.g. `var(--1isaui4-0)`
   */
  constructor();
  /** 
   * Creates a new CSS Variable with a custom defined name 
   * 
   * E.g. `var(--baseSize)`
   */
  constructor(uniqueName: string);
  /** 
   * Creates a new CSS Variable with a unique autogenerated name
   * and a fallback value
   * 
   * E.g. `var(--1isaui4-0, 12px)`
   */
  constructor(options: CSSVariableOptions<TValue>);
  /** 
   * Creates a new CSS Variable with a unique autogenerated name
   * and a fallback value
   * 
   * E.g. `var(--baseSize, 12px)`
   */
  constructor(uniqueName: string, options: CSSVariableOptions<TValue>);
  /*#__PURE__*/
  constructor(
    arg1?: string | CSSVariableOptions<TValue>,
    arg2?: CSSVariableOptions<TValue>
  ) {
    const args = [arg2, arg1];
    const optionArg = args.find(
      (arg): arg is CSSVariableOptions<TValue> => typeof arg === "object"
    );
    const name =
      "--" +
      (args.find((arg): arg is string => typeof arg === "string") ||
        // Fallback if babel plugin is missing
        Math.round(Math.random() * 10000).toString(16));
    const unit =
      ((optionArg || {}) as { unit: CSSUnit | undefined }).unit || "";
    super(`var(${name}${optionArg ? `, ${optionArg.value + unit}` : ""})`);
    this.name = name;
    this.unit = unit;
  }
  /** Returns the variable name e.g. `--baseSize` */
  getName() {
    return this.name;
  }
  /** Create a CSSObject e.g. `{ "--baseSize": '12px' }` */
  createStyle(newValue: TValue | CSSVariable<TValue>, unit?: CSSUnit) {
    return { [this.name]: newValue + (unit || this.unit) };
  }
  /** Create a CSSString e.g. `--baseSize:12px;` */
  createCSS(newValue: TValue | CSSVariable<TValue>, unit?: CSSUnit) {
    return `${this.name}:${newValue + (unit || this.unit)};`;
  }
  /** Returns the variable value e.g. `var(--baseSize, 12px)` */
  get val() {
    return String(this);
  }
}

/**
 * A theme structure groups multiple CSSVariable instances 
 * in a nested object structure e.g.:
 * 
 * ```ts
 * const theme = { 
 *   colors: {
 *     primary: new CSSVariable(),
 *     secondary: new CSSVariable()
 *   },
 *   spacings: {
 *     small: new CSSVariable(),
 *     large: new CSSVariable()
 *   }
 * }
 * ```
 */
type ThemeStructure = { [key: string]: CSSVariable | ThemeStructure };
type TCSSVariableValue<T> = T extends CSSVariable<infer U> ? U : T
/**
 * The ThemeValues type is a helper to map a ThemeStructure to a value type
 * to guarantee that the structure and values in serializeThemeValues match 
 */
type ThemeValues<TThemeStructure extends ThemeStructure> = {
  [Property in keyof TThemeStructure]: TThemeStructure[Property] extends CSSVariable
  ? TCSSVariableValue<TThemeStructure[Property]> | CSSVariable<TCSSVariableValue<TThemeStructure[Property]>>
  : TThemeStructure[Property] extends ThemeStructure
  ? ThemeValues<TThemeStructure[Property]>
  : never;
};

/**
 * Generate CSS for a Theme
 * 
 * @example
 * ```js
 * const theme = {
 *   colors: {
 *    primary: new CSSVariable(),
 *    secondary: new CSSVariable(),
 *  }
 * }
 * 
 * const brightThemeCSS = serializeThemeValues(theme, {
 *   colors: {
 *    primary: "#6290C3",
 *    secondary: "#C2E7DA",
 *  }
 * }) 
 * 
 * console.log(brightThemeCSS) // -> `--1isaui4-0:#6290C3; --1isaui4-1:#C2E7DA;`
 * ```
 */
export const serializeThemeValues = <TTheme extends ThemeStructure>(
  cssVariables: TTheme,
  cssVariableValues: ThemeValues<TTheme>
): string =>
  Object.keys(cssVariables)
    .map((key) =>
      typeof cssVariableValues[key] === "string"
        ? (cssVariables[key] as CSSVariable).createCSS(cssVariableValues[key] as string)
        : serializeThemeValues(
          cssVariables[key] as ThemeStructure,
          cssVariableValues[key] as ThemeValues<ThemeStructure>
        )
    )
    .join("");
