name: Release
on:
  push:
    branches:
      - main-TODO
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'test/**'
      - '.github/**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.19'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Test package
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release